### ISSUE TITLE
initialRenderIndex broke rendering elements when height is enough to show all of them

### ISSUE THREAD

**Issue by maxfarseer** [Flipkart/recyclerlistview#178]
### How to reproduce:

1.  Generate small list of elements (here in repo 3 items)
2.  Open the browser window with enough heigh to display all items
3.  Set up any initialRenderIndex different than 0 (1,2)

### Expected results:

All items displayed.

### Actual results:

No one element rendered

### Screenshots

https://monosnap.com/file/rLQjgBXDla3I67yYVIHNOWX0LCZAND - normal page, height not enough
https://monosnap.com/file/IooCvMWVxPyaHgm5ouTOSMadNYV1KP - blank page, when height is enough

---

[Demo repo](https://github.com/maxfarseer/recyclerlistview-initialRenderIndex-bug)

[Codesandbox](https://codesandbox.io/s/p3x3w4n45x)

**Comment by naqvitalha** [comment]
Can you provide a sample on codesandbox.io for me to check? That will help me look into this ASAP.

**Comment by maxfarseer** [comment]
@naqvitalha issue updated with link to codesandbox.

**Comment by naqvitalha** [comment]
Ah! Indeed it's bug :(
RLV expects a scroll event to trigger render in case of explicit offset. Which won't happen here.
Can you avoid giving an explicit index when items are few? I will try to fix this ASAP.

**Comment by yuvaraj119** [comment]
@naqvitalha  is this issue fixed any update.

**Comment by naqvitalha** [comment]
It is fixed in 1.4.0-beta.4, it might be a while before it is available outside beta since master has big changes

**Comment by yuvaraj119** [comment]
Even in beta, the issue there. Now the data gets loaded faster on scrolling but the older issue is still there.
waiting for stable release.

**Comment by Jyrno42** [comment]
I am currently using this as a workaround (both for `initialRenderIndex` and for `scrollTo` methods):

```
import { RecyclerListView as BaseRecyclerListView } from 'recyclerlistview';


class RecyclerListView extends BaseRecyclerListView {
    // Patch scrollToOffset so it does not overscroll
    /* eslint-disable */
    scrollToOffset(x, y, animate = false, pending = false) {
        if (this._scrollComponent) {
            const size = {
                height: 0,
                width: 0,

                ...this._initComplete ? this._virtualRenderer.getLayoutDimension() : {},
            };

            const visibleWidth = this._layout.width;
            const visibleHeight = this._layout.height;

            x = Math.min(x, size.width - visibleWidth);
            y = Math.min(y, size.height - visibleHeight);

            this._scrollComponent.scrollTo(x, y, animate);
        }
    }
    /* eslint-enable */
}

export default RecyclerListView;
```

**Comment by sbearben** [comment]
Also running into this page - any updates on a potential fix?

**Comment by arunreddy-flipkart** [comment]
This bug has been fixed in the current release. Closing

**Comment by quantumkv** [comment]
@arunreddy10 I am still able to reproduce this exact bug in v3.0.0. Is the fix included in this version?
